name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_call:
    inputs:
      build_type:
        description: "The CMake build type to use"
        required: false
        default: "Release"
        type: string

jobs:
  arm64-build:
    runs-on: macos-latest
    steps:
      
      - name: Check out code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build
        run: |
          bash bin/build.sh -r

      - name: Package creation
        run: |
          tar -czvf torchplugins_macOS_arm64.tar.gz torchplugins

      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with:
          name: torchplugins
          path: torchplugins_macOS_arm64.tar.gz

  x86_64-build:
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build
        run: |
          bash bin/build.sh -r

      - name: Package creation
        run: |
          tar -czvf torchplugins_macOS_x86_64.tar.gz torchplugins

      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with:
          name: torchplugins
          path: torchplugins_macOS_x86_64.tar.gz
